TfLite_sub_op add missing datatype support
MCW-Dev/tensorflow pull request #35
Opened 2024-07-19 11:16 UTC by RahulSundarMCW

- Adds bf16, f16 support sub function
 - Adds bf16, f16 unit tests

2024-08-02 11:38 UTC, RahulSundarMCW commented
We added a fix for convolution issue by defining a flag `(EIGEN_TFLITE)` in **conv.cc** to switch between `"Eigen/Core"` and `"EigenforTfLite"` libraries in **types.h** which was causing the conflict issue.
Can you please review it and let me know if any change is required?

2025-02-02 21:51 UTC, vamsimanchala requested changes

2025-02-02 21:51 UTC, vamsimanchala commented on tensorflow/lite/kernels/sub.cc
> +      output->type == kTfLiteInt16 && input_quantized) {
Why is `input1->quantization.type != kTfLiteNoQuantization `input_quantized`?

What if `input2->quantization.type != kTfLiteNoQuantization`? Can you please add some comments?

2025-02-02 21:54 UTC, vamsimanchala requested changes

2025-02-02 21:54 UTC, vamsimanchala commented on tensorflow/lite/kernels/sub.cc
> +        GetTensorShape(output), GetTensorData<int8_t>(output));
Are you able to reuse `EvalSubImpl<` ?

2025-02-04 11:16 UTC, RahulSundarMCW commented on tensorflow/lite/kernels/sub.cc
> +      output->type == kTfLiteInt16 && input_quantized) {
Included the comment

2025-02-04 11:41 UTC, RahulSundarMCW commented on tensorflow/lite/kernels/sub.cc
> +        GetTensorShape(output), GetTensorData<int8_t>(output));
Yes, I have modified to use EvalSubImpl

2025-02-04 14:18 UTC, vamsimanchala approved these changes

2025-03-21 03:58 UTC, merged